name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install g++
      - run: sudo apt install make
      - run: cd lab1_task2
      - run: cd lab1_task2
      - run: make
